language: php

php:
  - 5.3.3
  - 5.5

install:
  - php composer.phar install --dev --no-interaction --prefer-source

script:
  - php vendor/phpbb/translation-validator/src/Phpbb/TranslationValidator/PhpbbTranslationValidator.php validate ru --phpbb-version=3.1 --display-notices